/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Video for Jetpack.
 *
 * The Initial Developer of the Original Code is Mozilla Labs.
 * Portions created by the Initial Developer are Copyright (C) 2009-10
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *   Anant Narayanan <anant@kix.in>
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "nsILocalFile.idl"
#include "nsIOutputStream.idl"
#include "nsIPropertyBag2.idl"
#include "nsIDOMHTMLAudioElement.idl"
#include "nsIDOMCanvasRenderingContext2D.idl"

[scriptable, function, uuid(9d66a225-0134-4c6f-a6e2-466c899bdde4)]
interface nsIMediaStateObserver : nsISupports
{
    void onStateChange(in string state, in string args);
};

[scriptable, uuid(C4bb02e5-c1d7-4cde-90be-842424bfc1cc)]
interface nsIAudioSample : nsISupports
{
    attribute jsval frames;    
};

[scriptable, function, uuid(84dc6b74-56e6-44f9-8435-0647f71e7c2a)]
interface nsIAudioSampler : nsISupports
{
    void onSampleReceived(in nsIAudioSample sample);
};

[scriptable, uuid(c467b1f4-551c-4e2f-a6ba-cb7d792d1452)]
interface IMediaRecorder : nsISupports
{
    [implicit_jscontext]
    void beginSession(in nsIPropertyBag2 prop,
        in nsIDOMCanvasRenderingContext2D ctx,
        in nsIDOMHTMLAudioElement audio,
        in nsIAudioSampler slr,
        in nsIMediaStateObserver obs);
    void endSession();
    void beginRecording(in nsILocalFile file);
    void endRecording();
};
